### ISSUE TITLE
Unable to access CCTV IP camera

### ISSUE THREAD

**Issue by RATHINAMOORTHY** [awslabs/amazon-rekognition-video-analyzer#17]
Hi,
I have cloned **amazon-rekognition-video-analyzer** and installed all the prerequisite software's, got IAM user to access all necessary AWS services.

After setting the environment , I have configured the code and executed.

The **amazon-rekognition-video-analyzer** is working very fine with my in-build camera when i run the following command 
 **> pynt videocapture[20]**

But Iam unable to access the CCTV IP camera. The CCTV IP Camera has credentials too.
I have tried following commands, But not sending the video to kinesis stream. 

**> pynt videocaptureip["1*2.***.*.161", 20]** , as it have credentials I have also tried
> pynt videocaptureip["http://<username:password>@1*2.**.*.161", 20]
 But not working
 In capturing terminal it shows Capturing but not streaming to Kinesis service. 
 I have also tried by accessing a camera connected to the same network by providing it's IP. Iam able to ping. But it's raising I/O error.

Kindly help me to access the  CCTV IP Camera with credentials.

**Comment by RATHINAMOORTHY** [comment]
@moanany

**Comment by RATHINAMOORTHY** [comment]
@moanany

**Comment by moanany** [comment]
Hello,

Two things come to mind:

1) Are you sure this is the URL format, including the credentials, is supported by your camera? Cameras vary in terms of the specific URL to access the stream. Some research online could help. For example, you may find the URL format for your camera model [here](https://www.ispyconnect.com/sources.aspx).

2) Sometimes, the **pynt** tool has issues parsing URLs with special characters. If you are sure of the URL format of your IP camera, you can invoke the **video_cap_ipcam.py** python script directly instead of using **pynt**, passing the CCTV camera URL and capture rate.

Hope that helps.

**Comment by RATHINAMOORTHY** [comment]
Hi, Thanks

**Comment by RATHINAMOORTHY** [comment]
@moanany  Hello, Thanks for your quick response. I have tried both Steps 1 and 2 which you mentioned above. I can able to access the camera , but only getting static image, not in stream.
The URL which I used **http://1xx.xx.1xx.x1/jpg/image.jpg?size=3**
and command as **> python video_cap_ipcam.py http://1xx.xx.1xx.x1/jpg/image.jpg?size=3 20**
Request your help on this.

**Comment by RATHINAMOORTHY** [comment]
@moanany It's working! thanks ;-)

**Comment by RooCoder** [comment]
can you please provide the steps to make it up and running

**Comment by Moriuks** [comment]
to what @RooCoder said x2 would have been nice
